pipeline {
    agent any
        stages {
            stage ('First') {
                steps {
                    echo "This is my first stage!!!"
                }
            }

            stage ('Second') {
                steps {
                    echo "This is my second stage"
                }
            }
        }
    }
